#! /bin/sh
#
#
#
#
if [ $# != 2 ];then
	echo "make-setup ARCH VER"
	exit 0
fi
#
# Installation directories:目标文件安装目录
LR_INSTALL="/home/zhurish/workspace/route-platform/app/rt"
LR_PREFIX="--prefix=${LR_INSTALL} --localstatedir=${LR_INSTALL}/var "
#
#
#System types:
#  --build=BUILD     configure for building on BUILD [guessed]
#  --host=HOST       cross-compile to build programs to run on HOST [BUILD]
#  --target=TARGET   configure for building compilers for TARGET [HOST]
#
# for arm linux
#
#LR_TARGET="--build=i686 --host=arm-linux CC=arm-linux-gcc " 交叉编译为arm类型CPU
#
# for i686 linux(redhat) --target=i686-pc-linux-gnu (编译可执行文件名称前缀)
#
case $1 in
	"arm")
	LR_TARGET="--build=i686 --host=arm-linux CC=arm-linux-gcc "
	;;
	"x86")
	LR_TARGET="--build=i686-pc-linux-gnu --host=i686-pc-linux-gnu CC=gcc "
	;;
	*)
	echo "make-setup ARCH VER"
	exit 0
	;;
esac
case $2 in
	"0.99.22")
	OSPF_DEP_VER="--enable-opaque-lsa --enable-ospf-te "
	;;
	"0.99.24")
	OSPF_DEP_VER="--enable-opaque-lsa --enable-ospf-te "
	;;
	"1.0.0")
	OSPF_DEP_VER=" "
	;;	
	*)
	echo "make-setup ARCH VER"
	exit 0
	;;
esac
#
# for user 
#
#LR_USER="--enable-user=root --enable-group=root --enable-tcp-zebra --enable-zebra --enable-vtysh "
LR_USER="--enable-user=zhurish --enable-group=zhurish --enable-tcp-zebra --enable-zebra --disable-vtysh --enable-watchquagga "
#
# libraries to pass to the linker
#
LR_LIB_CONFIG="LIBS=-lpthread "
#
# Optional Features:

#
LR_CONFIG_1="--disable-babeld --disable-ripd  --disable-pimd --disable-ospf6d --disable-ripngd "
LR_CONFIG_2="--enable-ospfd --enable-ospfapi --enable-ospfclient --enable-ospf-dcn ${OSPF_DEP_VER} "
LR_CONFIG_3="--enable-olsrd --disable-ldpd --disable-rsvpd --disable-bgpd --disable-isisd --disable-isis-topology "
LR_CONFIG_4="--enable-utils --enable-vpnd --enable-vrrpd --enable-fpm --disable-rtadv --disable-irdp "
LR_CONFIG_5="--enable-lldpd --enable-configfile-mask=0664 --enable-logfile-mask=0664 "
LR_CONFIG_6="--enable-imi=65530 "

LR_CONFIG_7="--includedir=/home/zhurish/Downloads/work-dcn/linux-2.6.28.7/include "
#
# enable SNMP support (smux or agentx)
#
#LR_SNMP=" --enable-snmp=agentx"
LR_SNMP=""
#
#
#
LR_CONFIG=${LR_CONFIG_1}${LR_CONFIG_2}${LR_CONFIG_3}${LR_CONFIG_4}${LR_CONFIG_5}${LR_CONFIG_6}${LR_SNMP}
#
#
# make oem.bin file information
#
	
	LR_OEM=${LR_INSTALL}/etc/oem.bin
	LR_DATE=`date +"%Y-%m-%d"`
#
#
if [ ! -f "$LR_OEM" ];then
	echo "make oem information file:$LR_OEM"
	echo "
	Hello, this is routing-plaform (version $2).
	Copyright 2014/11 - ${LR_DATE} zhurish(zhurish@163.com), et al.
	Design it Base on (Quagga $2). " >>$LR_OEM
fi
#
#
#
#
#
echo ""
echo ./configure ${LR_PREFIX}${LR_TARGET}${LR_USER}${LR_CONFIG} ${LR_LIB_CONFIG}
echo ""
#
#
./configure ${LR_PREFIX}${LR_TARGET}${LR_USER}${LR_CONFIG} ${LR_LIB_CONFIG}
#
#
#
if test -d ".git"; then
GIT_AUTHER=`git log -1 --format=%an`
GIT_EMAIL=`git log -1 --format=%ae`
GIT_RELESE=`git branch | awk '{print $2}'`
GIT_VER=`git log -1 --format=%s | awk '{print $1}'`
GIT_COMMIT=`git log -1 --format=%H`

echo "#define GIT_SUFFIX	\"$GIT_VER (on $GIT_RELESE)\"" >> config.h
echo "#define GIT_INFO	\"commit:$GIT_COMMIT\"" >> config.h
fi

#
#

